package com.example.myapplication.model

sealed class CalculatorAction {
    data class Number(val value: String) : CalculatorAction()
    data class Operator(val value: String) : CalculatorAction()

    object Clear : CalculatorAction()
    object ClearEntry : CalculatorAction()
    object Backspace : CalculatorAction()
    object ToggleSign : CalculatorAction()
    object Decimal : CalculatorAction()
    object Percent : CalculatorAction()
    object Equals : CalculatorAction()

    object Reciprocal : CalculatorAction()
    object Square : CalculatorAction()
    object SquareRoot : CalculatorAction()

    data class ChangeMode(val mode: CalculatorMode) : CalculatorAction()

    object Sin : CalculatorAction()
    object Cos : CalculatorAction()
    object Tan : CalculatorAction()
    object Sec : CalculatorAction()
    object Csc : CalculatorAction()
    object Cot : CalculatorAction()
    object ToggleHyp : CalculatorAction()
    object ToggleTrigSecond : CalculatorAction()
    object Ln : CalculatorAction()
    object Log10 : CalculatorAction()
    object Floor : CalculatorAction()
    object Ceil : CalculatorAction()
    object Rand : CalculatorAction()
    object ToDms : CalculatorAction()
    object ToDeg : CalculatorAction()
    object Pi : CalculatorAction()
    object E : CalculatorAction()
    object Power : CalculatorAction()
    object ToggleSecond : CalculatorAction()
    object Abs : CalculatorAction()
    object Exp : CalculatorAction()
    object Factorial : CalculatorAction()
    object OpenParenthesis : CalculatorAction()
    object CloseParenthesis : CalculatorAction()
    object Power10 : CalculatorAction()
    object Cube : CalculatorAction()
    object CubeRoot : CalculatorAction()
    object YRoot : CalculatorAction()
    object Power2 : CalculatorAction()
    object LogBase : CalculatorAction()

    data class ChangeBase(val base: Int) : CalculatorAction()
    data class ChangeWordSize(val bits: Int) : CalculatorAction()
    data class ChangeProgrammerInputPane(val pane: ProgrammerInputPane) : CalculatorAction()
    data class ChangeProgrammerShiftMode(val mode: ProgrammerShiftMode) : CalculatorAction()
    data class ToggleProgrammerBit(val bitIndex: Int) : CalculatorAction()
    object Not : CalculatorAction()
    object And : CalculatorAction()
    object Or : CalculatorAction()
    object Nand : CalculatorAction()
    object Nor : CalculatorAction()
    object Xor : CalculatorAction()
    object ShiftLeft : CalculatorAction()
    object ShiftRight : CalculatorAction()
}
